### ISSUE TITLE
Developer dashboard page returns 404

### ISSUE THREAD

**Issue by onderweg** [Automatic/automatic-oauth-example-nodejs#1]
Hello,

The Developer Dashboard URL (https://www.automatic.com/developer/dashboard/) mentioned in the REST documentation results in a 404.
What's the correct URL for finding my client id? :)

**Comment by brendannee** [comment]
It should be developer.automatic.com/dashboard

Can you tell me where you found that incorrect link?

**Comment by onderweg** [comment]
The incorrect link is in the API documentation: https://developer.automatic.com/documentation/, in the text:

>For convenience, a formatted authorize URL including your client_id is provided for each application in the Developer Dashboard

**Comment by brendannee** [comment]
Thanks for pointing it out - this is updated in the docs.
